In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])

In [6]:
np.zeros((3,3))
np.ones((2,4))
np.eye(3)
np.arange(0,10,2)
np.linspace(0,1,5)
np.random.rand(3,2)
np.random.randn(3,2)

array([[-0.18526302, -2.06472345],
       [-0.30365693, -0.06432705],
       [-0.61440844, -0.04289803]])

In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [8]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b
a*b
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [9]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
np.dot(A,B)
A@B

array([[19, 22],
       [43, 50]])

In [10]:
arr=np.array([1,2,3,4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

np.float64(1.118033988749895)

In [11]:
arr=np.array([1,2,3,4,5])
arr[0]
arr[1:4]
arr[::2]

array([1, 3, 5])

In [12]:
arr=np.array([1,2,3,4,5])
mask=arr>3
arr[mask]

array([4, 5])

In [13]:
arr=np.arange(6)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
a=np.array([1,2])
b=np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [15]:
np.vstack((a,b))
np.hstack((a,b))

array([1, 2, 3, 4])

In [16]:
a=np.array([1,2,3])
a+5

array([6, 7, 8])

In [17]:
np.save('array.npy',arr)

In [19]:
loaded_arr=np.load('array.npy')